### ISSUE TITLE
Add a Dark Mode

### ISSUE THREAD

**Issue by russellpeiris** [pawan-live/timetable-app#54]
Add a dark theme for those who prefer dark theme

**Comment by methmal66** [comment]
The first interaction greeting works. Yay!

**Comment by pawan-live** [comment]
Noice

**Comment by pawan-live** [comment]
Check branch #59 for progress 👀

**Comment by russellpeiris** [comment]
PR #60 allows you to toggle between light and dark theme.
PR #59 depended on the browser's default theme.

**Comment by pawan-live** [comment]
Love the idea and the work, but as I see, you have made a copy of the whole CSS file and edited the components to be dark. But if we need to edit the main CSS file later on, the dark.css file too should be edited with the same changes since the CSS file linked to the HTML changes upon toggle button click.

I'd suggest creating a dark.CSS file only with the classes that needs to be updated, then keep all the basic styles the same, and adding the dark.css file into the HTML on button click. So only the necessary classes get updated.

**Comment by pawan-live** [comment]
Will address this in phase 2
